spring:
  cloud:
    azure:
      servicebus:
        connection-string: ${SERVICE_BUS_CONNECTION_STRING}
    function:
      definition: supply
    stream:
      bindings:
        supply-out-0:
          destination: dummy.queue.test
      servicebus:
        bindings:
          supply-out-0:
            producer:
              entity-type: queue
      poller:
        fixed-delay: 1000
        initial-delay: 0