spring:
  cloud:
    azure:
      servicebus:
        connection-string: ${SERVICE_BUS_CONNECTION_STRING}
    function:
      definition: consume;supply
    stream:
      bindings:
        consume-in-0:
          destination: dummy.queue.test
        supply-out-0:
          destination: dummy.queue.test
      servicebus:
        bindings:
          consume-in-0:
            consumer:
              auto-complete: false
          supply-out-0:
            producer:
              entity-type: queue
      poller:
        fixed-delay: 1000
        initial-delay: 0